#!/usr/bin/env python3
"""
Daily Micro Learning Script
Triggered by: cron / manual / skill
Updates: memory/agents/{agent}/LEARNING.md
"""

import os
import sys
import json
from datetime import datetime
from pathlib import Path

BASE_DIR = Path("/Users/linweihao/project/MuskOrchestrator")
MEMORY_DIR = BASE_DIR / "memory" / "agents"
HEARTBEAT_FILE = BASE_DIR / "HEARTBEAT.md"

def get_today():
    return datetime.now().strftime("%Y-%m-%d")

def read_heartbeat():
    """Read current learning focus from HEARTBEAT"""
    if HEARTBEAT_FILE.exists():
        content = HEARTBEAT_FILE.read_text(encoding='utf-8')
        # Extract current focus
        focus = "General"
        for line in content.split('\n'):
            if line.startswith('**Current Focus**:'):
                focus = line.split(':', 1)[1].strip()
                break
        return focus
    return "General"

def update_agent_learning(agent_name, content_type, source, insight):
    """Append learning entry to agent's LEARNING.md"""
    agent_dir = MEMORY_DIR / agent_name
    agent_dir.mkdir(parents=True, exist_ok=True)

    learning_file = agent_dir / "LEARNING.md"

    entry = f"""
## {get_today()} - {content_type}

**Source**: {source}
**Focus**: {read_heartbeat()}

{insight}

---
"""

    if learning_file.exists():
        with open(learning_file, 'a', encoding='utf-8') as f:
            f.write(entry)
    else:
        header = f"# {agent_name.upper()} - Learning Log\n\n> Daily micro-learning records\n\n"
        with open(learning_file, 'w', encoding='utf-8') as f:
            f.write(header + entry)

def main():
    """Execute daily micro learning"""
    print(f"[{get_today()}] Starting Daily Micro Learning...")
    print(f"Current Focus: {read_heartbeat()}")

    # This is a scaffold - actual implementation would spawn subagents
    # For now, just ensure structure exists

    agents = ["analyst", "engineer", "mentor", "creator"]

    for agent in agents:
        agent_dir = MEMORY_DIR / agent
        agent_dir.mkdir(parents=True, exist_ok=True)
        print(f"  ✓ Checked {agent} learning directory")

    print(f"\n[{get_today()}] Daily Micro Learning scaffold ready.")
    print("Note: Actual learning content should be generated by spawning subagents.")

if __name__ == "__main__":
    main()
