#!/usr/bin/env python3
"""
Weekly Deep Review Script
Triggered by: cron (Sunday 22:00) / manual / skill
Generates: memory/reports/weekly/YYYY-WXX-Agent进化报告.md
"""

import os
import sys
import json
from datetime import datetime
from pathlib import Path

BASE_DIR = Path("/Users/linweihao/project/MuskOrchestrator")
MEMORY_DIR = BASE_DIR / "memory" / "agents"
REPORTS_DIR = BASE_DIR / "memory" / "reports" / "weekly"
HEARTBEAT_FILE = BASE_DIR / "HEARTBEAT.md"

def get_week_info():
    today = datetime.now()
    return today.strftime("%Y-W%W"), today.strftime("%Y-%m-%d")

def read_agent_learning(agent_name):
    """Read agent's LEARNING.md content"""
    learning_file = MEMORY_DIR / agent_name / "LEARNING.md"
    if learning_file.exists():
        return learning_file.read_text(encoding='utf-8')
    return f"*{agent_name} has no learning records yet.*"

def generate_weekly_report():
    """Generate weekly evolution report"""
    week, today = get_week_info()
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)

    report_file = REPORTS_DIR / f"{week}-Agent进化报告.md"

    agents = ["planner", "engineer", "analyst", "mentor", "creator", "reviewer"]

    report_content = f"""# Agent Evolution Report - {week}

**Generated**: {today}
**System**: MuskOrchestrator v3.0

---

## Executive Summary

Weekly review of all agent learning and evolution progress.

## Agent Learning Summary

"""

    for agent in agents:
        report_content += f"""
### @{agent}

{read_agent_learning(agent)}

"""

    report_content += f"""
---

## Key Insights

*To be filled during weekly review*

## Cross-Agent Knowledge Fusion

*To be filled during weekly review*

## Next Week Priorities

*To be filled during weekly review*

---

*Report generated by weekly_review.py*
"""

    report_file.write_text(report_content, encoding='utf-8')
    print(f"Generated: {report_file}")
    return report_file

def main():
    """Execute weekly deep review"""
    week, today = get_week_info()
    print(f"[{today}] Starting Weekly Deep Review for {week}...")

    report = generate_weekly_report()

    print(f"\n[{today}] Weekly Deep Review completed.")
    print(f"Report saved to: {report}")

if __name__ == "__main__":
    main()
